config/routes.rb
Rails.application.routes.draw do

  resources :papers do
    member do
      post 'start_review'
      post 'reject'
    end

    collection do
      get 'recent'
      get 'popular'
      get 'submitted'
    end
  end

  get '/papers/:id/status.svg', :to => "papers#status", :format => "svg", :as => 'status_badge'
  get '/papers/:doi/status.svg', :to => "papers#status", :format => "svg", :constraints => { :doi => /10.21105\/joss\.\d{5}/}
  get '/papers/:doi', :to => "papers#show", :constraints => {:doi => /.*/}

  post '/update_profile', :to => "home#update_profile"
  get '/about', :to => 'home#about', :as => 'about'
  get '/profile', :to => 'home#profile', :as => 'profile'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get "/signout" => "sessions#destroy", :as => :signout

  root :to => 'home#index'
end

app/models/paper.rb
class Paper < ActiveRecord::Base

  belongs_to  :submitting_author,
              :class_name => 'User',
              :validate => true,
              :foreign_key => "user_id"

  include AASM

  aasm :column => :state do
    state :submitted, :initial => true
    state :under_review, :before_enter => :create_review_issue
    state :review_completed
    state :superceded
    state :accepted
    state :rejected

    event :reject do
      transitions :to => :rejected
    end

    event :start_review do
      transitions :from => :submitted, :to => :under_review
    end

    event :accept do
      transitions :to => :accepted
    end
  end

  VISIBLE_STATES = [
    "accepted",
    "superceded"
  ]

  IN_PROGRESS_STATES = [
    "submitted",
    "under_review"
  ]

  default_scope  { order(:created_at => :desc) }
  scope :recent, lambda { where('created_at > ?', 1.week.ago) }
  scope :submitted, lambda { where('state = ?', 'submitted') }
  scope :in_progress, -> { where(:state => IN_PROGRESS_STATES) }
  scope :visible, -> { where(:state => VISIBLE_STATES) }
  scope :everything, lambda { where('state != ?', 'rejected') }

  before_create :set_sha
  after_create :notify_editors


  validates_presence_of :title
  validates_presence_of :repository_url, :message => "^Repository address can't be blank"
  validates_presence_of :software_version, :message => "^Version can't be blank"
  validates_presence_of :body, :message => "^Description can't be blank"

  def notify_editors
    Notifications.submission_email(self).deliver_now
  end

  def self.featured
    # TODO: Make this a thing
    Paper.first
  end

  def self.popular
    recent
  end

  def to_param
    sha
  end

  def pretty_repository_name
    if repository_url.include?('github.com')
      name, owner = repository_url.scan(/(?<=github.com\/).*/i).first.split('/')
      return "#{name} / #{owner}"
    else
      return repository_url
    end
  end

  def pretty_doi
    return "DOI pending" unless archive_doi

    matches = archive_doi.scan(/\b(10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+)\b/).flatten

    if matches.any?
      return matches.first
    else
      return archive_doi
    end
  end

  # Make sure that DOIs have a full http URL
  # e.g. turn 10.6084/m9.figshare.828487 into http://dx.doi.org/10.6084/m9.figshare.828487
  def doi_with_url
    return "DOI pending" unless archive_doi

    bare_doi = archive_doi[/\b(10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+)\b/]

    if archive_doi.include?("http://dx.doi.org/")
      return archive_doi
    elsif bare_doi
      return "http://dx.doi.org/#{bare_doi}"
    else
      return archive_doi
    end
  end

  def create_review_issue
    return false if review_issue_id
    issue = GITHUB.create_issue("openjournals/joss-reviews",
                                "Submission: #{self.title}",
                                review_body,
                                { :labels => "review" })

    set_review_issue(issue)
  end

  def set_review_issue(issue)
    self.update_attribute(:review_issue_id, issue.number)
  end

  def update_review_issue(comment)
    GITHUB.add_comment("openjournals/joss-reviews", self.review_issue_id, comment)
  end

  def review_url
    "https://github.com/openjournals/joss-reviews/issues/#{self.review_issue_id}"
  end

  def review_body
    ActionView::Base.new(Rails.configuration.paths['app/views']).render(
      :template => 'shared/review_body', :format => :txt,
      :locals => { :paper => self }
    )
  end

  def pretty_state
    state.humanize.downcase
  end

  # Returns DOI with URL e.g. "http://dx.doi.org/10.21105/joss.00001"
  def cross_ref_doi_url
    "http://dx.doi.org/#{doi}"
  end

  def status_badge
    case self.state.to_s
    when "submitted"
      '<svg xmlns="http://www.w3.org/2000/svg" width="108" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="108" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h40v20H0z"/><path fill="#007ec6" d="M40 0h68v20H40z"/><path fill="url(#b)" d="M0 0h108v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="20" y="15" fill="#010101" fill-opacity=".3">JOSS</text><text x="20" y="14">JOSS</text><text x="73" y="15" fill="#010101" fill-opacity=".3">Submitted</text><text x="73" y="14">Submitted</text></g></svg>'
    when "under_review"
      '<svg xmlns="http://www.w3.org/2000/svg" width="129" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="129" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h40v20H0z"/><path fill="#dfb317" d="M40 0h89v20H40z"/><path fill="url(#b)" d="M0 0h129v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="20" y="15" fill="#010101" fill-opacity=".3">JOSS</text><text x="20" y="14">JOSS</text><text x="83.5" y="15" fill="#010101" fill-opacity=".3">Under Review</text><text x="83.5" y="14">Under Review</text></g></svg>'
    when "review_completed"
      '<svg xmlns="http://www.w3.org/2000/svg" width="150" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="150" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h40v20H0z"/><path fill="#dfb317" d="M40 0h110v20H40z"/><path fill="url(#b)" d="M0 0h150v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="20" y="15" fill="#010101" fill-opacity=".3">JOSS</text><text x="20" y="14">JOSS</text><text x="94" y="15" fill="#010101" fill-opacity=".3">Review Complete</text><text x="94" y="14">Review Complete</text></g></svg>'
    when "accepted"
      "<svg xmlns='http://www.w3.org/2000/svg' width='168' height='20'><linearGradient id='b' x2='0' y2='100%'><stop offset='0' stop-color='#bbb' stop-opacity='.1'/><stop offset='1' stop-opacity='.1'/></linearGradient><mask id='a'><rect width='168' height='20' rx='3' fill='#fff'/></mask><g mask='url(#a)'><path fill='#555' d='M0 0h39v20H0z'/><path fill='#4c1' d='M39 0h129v20H39z'/><path fill='url(#b)' d='M0 0h168v20H0z'/></g><g fill='#fff' text-anchor='middle' font-family='DejaVu Sans,Verdana,Geneva,sans-serif' font-size='11'><text x='19.5' y='15' fill='#010101' fill-opacity='.3'>JOSS</text><text x='19.5' y='14'>JOSS</text><text x='102.5' y='15' fill='#010101' fill-opacity='.3'>#{self.doi}</text><text x='102.5' y='14'>#{self.doi}</text></g></svg>"
    when "rejected"
      '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="100" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h40v20H0z"/><path fill="#e05d44" d="M40 0h60v20H40z"/><path fill="url(#b)" d="M0 0h100v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="20" y="15" fill="#010101" fill-opacity=".3">JOSS</text><text x="20" y="14">JOSS</text><text x="69" y="15" fill="#010101" fill-opacity=".3">Rejected</text><text x="69" y="14">Rejected</text></g></svg>'
    else
      '<svg xmlns="http://www.w3.org/2000/svg" width="102" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="102" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h40v20H0z"/><path fill="#9f9f9f" d="M40 0h62v20H40z"/><path fill="url(#b)" d="M0 0h102v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="20" y="15" fill="#010101" fill-opacity=".3">JOSS</text><text x="20" y="14">JOSS</text><text x="70" y="15" fill="#010101" fill-opacity=".3">Unknown</text><text x="70" y="14">Unknown</text></g></svg>'
    end
  end

private

  def set_sha
    self.sha = SecureRandom.hex
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_filter :require_user, :only => %w(new create update)
  before_filter :require_complete_profile, :only => %w(create)
  before_filter :require_admin_user, :only => %w(start_review archive)

  def recent
    @papers = Paper.visible.paginate(
                :page => params[:page],
                :per_page => 10
              )

    @selected = "recent"

    respond_to do |format|
      format.atom { render :template => 'papers/index' }
      format.json { render :json => @papers }
      format.html { render :template => 'papers/index' }
    end
  end

  def index
    @papers = Paper.everything.paginate(
                :page => params[:page],
                :per_page => 10
              )

    @popular_papers = Paper.visible.paginate(
                :page => params[:page],
                :per_page => 10
              )

    @recent_papers = @popular_papers

    @submitted_papers = Paper.in_progress.paginate(
                :page => params[:page],
                :per_page => 10
              )
    @selected = "all"

    respond_to do |format|
      format.atom { render :template => 'papers/index' }
      format.json { render :json => @papers }
      format.html { render :template => 'papers/index' }
    end
  end

  def popular
    # TODO: Need to order by popularity here
    @papers = Paper.visible.paginate(
                :page => params[:page],
                :per_page => 10
              )

    @selected = "popular"

    respond_to do |format|
      format.atom { render :template => 'papers/index' }
      format.json { render :json => @papers }
      format.html { render :template => 'papers/index' }
    end
  end

  def submitted
    @papers = Paper.in_progress.paginate(
                :page => params[:page],
                :per_page => 10
              )

    @selected = "submitted"

    respond_to do |format|
      format.atom { render :template => 'papers/index' }
      format.json { render :json => @papers }
      format.html { render :template => 'papers/index' }
    end
  end

  def start_review
    @paper = Paper.find_by_sha(params[:id])

    if @paper.start_review!
      flash[:notice] = "Review started"
      redirect_to paper_path(@paper)
    else
      flash[:error] = "Review could not be started"
      redirect_to paper_path(@paper)
    end
  end

  def reject
    @paper = Paper.find_by_sha(params[:id])

    if @paper.reject!
      flash[:notice] = "Paper rejected"
      redirect_to paper_path(@paper)
    else
      flash[:error] = "Paper could not be rejected"
      redirect_to paper_path(@paper)
    end
  end

  def new
    @paper = Paper.new
  end

  def show
    if params[:doi] && valid_doi?
      @paper = Paper.find_by_doi(params[:doi])
    else
      @paper = Paper.find_by_sha(params[:id])
    end
  end

  def valid_doi?
    if params[:doi] && params[:doi].include?("10.21105")
      return true
    else
      return false
    end
  end

  def create
    @paper = Paper.new(paper_params)

    @paper.submitting_author = current_user

    if @paper.save
      redirect_to paper_path(@paper)
    else
      render :action => :new
    end
  end

  def status
    if params[:doi] && valid_doi?
      @paper = Paper.find_by_doi(params[:doi])
    else
      @paper = Paper.find_by_sha(params[:id])
    end

    # TODO: Remove these SVGs from the controller
    if @paper
      svg = @paper.status_badge
    else
      svg = '<svg xmlns="http://www.w3.org/2000/svg" width="102" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="a"><rect width="102" height="20" rx="3" fill="#fff"/></mask><g mask="url(#a)"><path fill="#555" d="M0 0h40v20H0z"/><path fill="#9f9f9f" d="M40 0h62v20H40z"/><path fill="url(#b)" d="M0 0h102v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"><text x="20" y="15" fill="#010101" fill-opacity=".3">JOSS</text><text x="20" y="14">JOSS</text><text x="70" y="15" fill="#010101" fill-opacity=".3">Unknown</text><text x="70" y="14">Unknown</text></g></svg>'
    end

    if stale?(@paper)
      render :inline => svg
    end
  end

  private

  def paper_params
    params.require(:paper).permit(:title, :repository_url, :archive_doi, :software_version, :body)
  end
end

app/helpers/papers_helper.rb
module PapersHelper
  def selected_class(tab_name)
    if controller.action_name == tab_name
      "selected"
    end
  end

  def badge_link(paper)
    if paper.accepted?
      return paper.cross_ref_doi_url
    else
      return paper.review_url
    end
  end

  def formatted_body(paper, length=nil)
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::MarkdownFilter,
      HTML::Pipeline::SanitizationFilter
    ]

    if length
      body = paper.body.truncate(length, separator: /\s/)
    else
      body = paper.body
    end

    result = pipeline.call(body)
    result[:output].to_s.html_safe
  end
end

app/views/papers/_admin.html.erb
<% if paper.review_issue_id %>
  <%= link_to "View review issue &raquo;".html_safe, paper.review_url, :target => "_blank" %>
 <% end %>

<% if current_user.admin? %>
  <% unless paper.review_issue_id %>
    <%= button_to "Start review", start_review_paper_path(paper), :class => "btn btn-primary left start-review" %>
    <%= button_to "Reject paper", reject_paper_path(paper), :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  <% end %>
<% end %>

app/views/papers/_list.html.erb
<% papers.each do |paper| %>
<div class="list-paper columns">
  <div class="details three-fourths column">
    <span class="octicon octicon-mark-github"></span><h2 class="paper-title"><%= link_to paper.pretty_repository_name, paper_path(paper) %><a href="<%= badge_link(paper) %>"><img src="http://joss.theoj.org/papers/<%= paper.sha %>/status.svg"></a></h2>
    <%= formatted_body(paper, 200) %>
  </div>

  <div class="meta one-fourth column">
    <%= link_to paper.pretty_doi, paper.doi_with_url, :target => "_blank", :class => "doi" %><span class="octicon octicon-link-external"></span>
  </div>
</div>
<% end %>

app/views/papers/_status.html.erb
<div class="flash flash-warn">
  <% case paper.state %>
  <% when "submitted" %>
  <p>This paper is <strong><%= paper.pretty_state %></strong> but the
    review hasn't started.</p>
  <% when "under_review" %>
  <p>This paper is <strong><%= paper.pretty_state %></strong> which means
    review has begun. You can track the progress of this review on
    GitHub over <%= link_to "here &raquo;".html_safe, paper.review_url %></p>
  <% when "review_completed" %>
  <p>This paper is <strong><%= paper.pretty_state %></strong> which means
    the review is completed and is awaiting review by the editor.
    You can track the progress of this paper on
    GitHub over <%= link_to "here &raquo;".html_safe, paper.review_url %></p>
  <% when "accepted" %>
  <p>This paper is <strong><%= paper.pretty_state %></strong> which means
    the review is completed and it has been accepted into The Journal
    of Open Source Software. You can view the review of this paper on
    GitHub over <%= link_to "here &raquo;".html_safe, paper.review_url %></p>
  <% when "rejected" %>
  <p>This paper is <strong><%= paper.pretty_state %></strong> which means
    is has not been accepted into The Journal of Open Source Software.</p>
  <% end %>
</div>

app/views/papers/index.html.erb
<div class="wrapper">
  <div class="all-papers">
    <div class="filter-menu">
      <div class="tabnav">
        <nav class="tabnav-tabs">
          <%# link_to "Recent papers (#{Paper.recent.visible.count})", recent_papers_path, :class => "tabnav-tab #{selected_class('recent')}" %>
          <%= link_to "Accepted papers (#{Paper.visible.count})", popular_papers_path, :class => "tabnav-tab #{selected_class('popular')}" %>
          <%= link_to "Submitted papers (#{Paper.in_progress.count})", submitted_papers_path, :class => "tabnav-tab #{selected_class('submitted')}" %>
          <%= link_to "All papers (#{Paper.everything.count})", papers_path, :class => "tabnav-tab #{selected_class('index')}" %>
        </nav>
      </div>
    </div>

    <%= render :partial => "list", :locals => { :papers => @papers } %>
    <div class="pagination centered">
      <%= will_paginate @papers %>
    </div>
  </div>
</div>

app/views/papers/new.html.erb
<div class="wrapper">
  <div class="new-paper">
    <h1>Submit software for review</h1>

    <div class="columns new-paper-form">
      <div class="column three-thirds flash flash-warn">
        <strong>Before you submit</strong>
        <p>Please make sure you've read the <a href="/about#author_guidelines">submission
          instructions</a> before submitting. In particular please make sure there is a
          <code>paper.md</code> present in your repository that is structured
          <a href="/about#paper_structure">like this</a>. We promise this will make things go much
          more quickly during the review process <span class="octicon octicon-rocket"></span></p>
      </div>

      <%= form_for @paper do |f| %>
        <%= render :partial => "shared/errors", :locals => { :object => @paper } if @paper.errors.any? %>
        <dl class="one-third column">
          <dt><%= f.label :title %></dt>
          <dt><%= f.text_field :title, :placeholder => "What's the title of this paper?" %></dt>
        </dl>
        <dl class="one-third column">
          <dt><%= f.label "Repository Address" %></dt>
          <dt><%= f.text_field :repository_url, :placeholder => "What's the URL of your software?" %></dt>
        </dl>
        <dl class="one-third column">
          <dt><%= f.label "Version" %></dt>
          <dt><%= f.text_field :software_version, :placeholder => "e.g. v1.0.0" %></dt>
        </dl>

        <dl class="clear full">
          <dt><%= f.label "Description" %></dt>
          <dt><%= f.text_area :body, :rows => "7",
                              :placeholder => "Please give short (1-2 line) description of your software." %></dt>
        </dl>

        <label>
          <input type="checkbox" id="author-check">
          I certify that I am submitting software for which I am a primary author
        </label>
        <div class="form-actions">
          <%= submit_tag("Submit paper", :class => "btn disabled", :id => "author-submit") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/papers/show.html.erb
<div class="wrapper">
  <div class="show-paper">
    <% unless @paper.doi? %>
    <%= render :partial => "status", :locals => { :paper => @paper } %>
    <%= render :partial => "papers/admin", :locals => { :paper => @paper } if current_user %>
    <% end %>
    <div class="columns">
      <% if @paper.doi? %>
      <%= @paper.paper_body.html_safe %>
      <% else %>
      <div class="paper-body"><%= formatted_body(@paper) %></div>
      <div class="one-half column paper-meta">
        <p><strong>Repository Address</strong>: <%= link_to @paper.repository_url, @paper.repository_url %></p>
      </div>
      <div class="one-half column paper-meta">
        <p><strong>Archive DOI</strong>: <%= link_to @paper.archive_doi, @paper.doi_with_url %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/papers/status.html.erb
<% if @paper %>
  <%= link_to image_tag(status_badge_for(@paper)), paper_url(@paper) %>
<% else %>
  <%= image_tag(status_badge_for(@paper)) %>
<% end %>